### ISSUE TITLE
关于Lora微调中参数设置的问题。

### ISSUE THREAD

**Issue by swordqiqi** [zyang1580/CoLLM#10]
您好！
请问，在Lora微调时参数pretrained_path时是如何设置的呢，设置为None还是0925-OODv2_lgcn_book_best_model_d256lr-0.0001wd1e-07.pth这样的文件路径呢。我的理解是应该设置为None，因为第一次微调不加入embedding，但是这样不能运行。

**Comment by zyang1580** [comment]
是指rec model的pretrained_path么？是的话，加与不加应该是没有影响的。不能运行报什么错呢？

**Comment by swordqiqi** [comment]
已经解决了，谢谢！！

**Comment by Jrui66** [comment]
> 已经解决了，谢谢！！
我也遇到了这个问题，请问您是怎么解决的呢

**Comment by swordqiqi** [comment]
lora微调时将checkpoint_path那行注释掉，pretrained_path填什么内容都可以。就行了
