### ISSUE TITLE
ValueError: Input contains NaN.

### ISSUE THREAD

**Issue by manjusaka-L** [zyang1580/CoLLM#11]
When I run the program on Amazon Book to 11 epochs, the loss becomes nan.
All the settings are default. The GPU is A100 *1.

Can you give some suggestions?

**Comment by manjusaka-L** [comment]
BTW, can we access the pre-trained weights?

**Comment by zyang1580** [comment]
> BTW, can we access the pre-trained weights?

I will upload the pre-trained weights when I am free.

**Comment by zyang1580** [comment]
> When I run the program on Amazon Book to 11 epochs, the loss becomes nan. All the settings are default. The GPU is A100 *1.
> 
> Can you give some suggestions?

What learning rate are you using? You might try tuning it down.

**Comment by manjusaka-L** [comment]
Thanks for your suggestions!
