### ISSUE TITLE
About the collaborative model of BinLLM

### ISSUE THREAD

**Issue by wzhwzhwzh0921** [zyang1580/CoLLM#17]
BinLLM is not open-sourced. Which model is the collaborative model of BinLLM? Can author share the parameters of Binarization & compression layer?

**Comment by zyang1580** [comment]
- Now, BinLLM is open-sourced. You can find it at https://github.com/zyang1580/BinLLM
- The trained models will be uploaded to the following link: https://rec.ustc.edu.cn/share/ddf0ccf0-5fb3-11ef-93eb-23d2eed3b4d2

**Comment by zyang1580** [comment]
Our trained models have been uploaded to the above link.

**Comment by wzhwzhwzh0921** [comment]
Thank you !
