### ISSUE TITLE
Inconsistency of ML-1M statistics in paper and released propcessed dataset

### ISSUE THREAD

**Issue by dekoponTree** [zyang1580/CoLLM#2]
The paper reported that ML-1M dataset have 839 users and 3,256 items.
<img width="566" alt="image" src="https://github.com/zyang1580/CoLLM/assets/119666897/84e3e99e-bbe0-4b45-a3fe-9d5637dd714c">

The statistics is inconsistent with released datasets, which can be reproduced via following scripts
```python
import pandas as pd

train_ = pd.read_pickle('train_ood2.pkl')
valid_ = pd.read_pickle('valid_ood2.pkl')
test_ = pd.read_pickle('test_ood2.pkl')

uids = set(train_.uid.unique()) | set(valid_.uid.unique()) | set(test_.uid.unique())
iids = set(train_.iid.unique()) | set(valid_.iid.unique()) | set(test_.iid.unique())

print(len(uids), len(iids)) # 838, 3255
```

**Comment by zyang1580** [comment]
The statistics include one additional padding ID.
