### ISSUE TITLE
What is the dataset config format

### ISSUE THREAD

**Issue by anjiajun39** [zyang1580/CoLLM#3]
Hello, When I run your code in my server there is a problem, it need a dataset config file and I can't find this file in the code.

The error in the file `minigpt4/datasets/builders/rec_pair_builder.py`

The error said:
`FileNotFoundError: [Errno 2] No such file or directory: './CoLLM/minigpt4/configs/datasets/movielens/default.yaml'`

How I can write this file or get it.

Thanks!

**Comment by zyang1580** [comment]
I have added an example.
Please see this [file](https://github.com/zyang1580/CoLLM/tree/main/minigpt4/configs/datasets/movielens).

**Comment by anjiajun39** [comment]
Thanks! I can run it now.
