### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by NicholasEinstein** [zyang1580/CoLLM#7]
作者你好，请问3090能不能跑你的代码呢，你用的两张A100的训练时间大概是多久呢

**Comment by NicholasEinstein** [comment]
如果采用llama2-7b模型 alpaca lora的方式会不会更快一点

**Comment by zyang1580** [comment]
3090
没有尝试过，A40应该可以，A100的运行时间我记得阶段一的范围在6-20小时，阶段二比较快，具体多少不记得了。（collm模型架构部分的代码可以简化下，等一段时间更新简化后的版本）

alpaca lora的方式没有尝试，过段时间空闲的时候我尝试下。

NicholasEinstein ***@***.***> 于2024年3月9日周六 00:17写道：
