### ISSUE TITLE
hot and cold datasets

### ISSUE THREAD

**Issue by NicholasEinstein** [zyang1580/CoLLM#9]
Hello author, I noticed that your code does not seem to provide the hot and cold datasets mentioned in the paper. Is it missing? Sincerely looking forward to your supplementation

**Comment by zyang1580** [comment]
Thank you for your question. There is no need for an additional hot and cold dataset. You can directly obtain the hot and cold data by filtering the "not_cold" (or "warm") field. Please refer to the code [here].(https://github.com/zyang1580/CoLLM/blob/1ac29077d885cfeb179ee57a972d99580946b687/minigpt4/datasets/datasets/rec_datasets.py#L444)
